# Generated by Django 5.1 on 2024-08-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('First_name', models.CharField(max_length=250)),
                ('Last_name', models.CharField(max_length=250)),
            ],
        ),
    ]
