# Generated by Django 5.1 on 2024-08-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='First_name',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Last_name',
            new_name='Tittle',
        ),
    ]
